#! /usr/bin/env bash

echo "== deploy s3 bucket via CFN"

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file /workspace/AWS-Examples/s3/iac/cfn/template.yaml \
--no-execute-changeset \
--stack-name $STACK_NAME